=== Zvord/Censor.DV/mySchema.json
{
	"definitions": {},
	"$schema": "http://json-schema.org/draft-07/schema#", 
	"$id": "https://example.com/object1664436200.json", 
	"title": "Root", 
	"type": "object",
	"required": [
		"class_name",
		"enum_name",
		"covergroup_name",
		"fsm_descriptions",
		"scenarios"
	],
	"properties": {
		"class_name": {
			"$id": "#root/class_name", 
			"title": "Class_name", 
			"type": "string",
			"default": "",
			"pattern": "^.*$"
		},
		"enum_name": {
			"$id": "#root/enum_name", 
			"title": "Enum_name", 
			"type": "string",
			"default": "",
			"pattern": "^.*$"
		},
		"covergroup_name": {
			"$id": "#root/cg_name", 
			"title": "Covergroup_name", 
			"type": "string",
			"default": "",
			"pattern": "^.*$"
		},
		"fsm_descriptions": {
			"$id": "#root/fsm_descriptions", 
			"title": "Fsm_descriptions", 
			"type": "array",
			"default": [],
			"items":{
				"$id": "#root/fsm_descriptions/items", 
				"title": "Items", 
				"type": "object",
				"required": [
					"source_name",
					"valid_states"
				],
				"properties": {
					"source_name": {
						"$id": "#root/fsm_descriptions/items/source_name", 
						"title": "Source_name", 
						"type": "string",
						"default": "",
						"pattern": "^.*$"
					},
					"valid_states": {
						"$id": "#root/fsm_descriptions/items/valid_states", 
						"title": "Valid_states", 
						"type": "array",
						"default": [],
						"items":{
							"$id": "#root/fsm_descriptions/items/valid_states/items", 
							"title": "Items", 
							"type": "string",
							"default": "",
							"pattern": "^.*$"
						}
					}
				}
			}

		},
		"scenarios": {
			"$id": "#root/scenarios", 
			"title": "Scenarios", 
			"type": "array",
			"default": [],
			"items":{
				"$id": "#root/scenarios/items", 
				"title": "Items", 
				"type": "object",
				"required": [
					"description",
					"scenario_name",
					"signal"
				],
				"properties": {
					"description": {
						"$id": "#root/scenarios/items/description", 
						"title": "Description", 
						"type": "string",
						"default": "",
						"pattern": "^.*$"
					},
					"scenario_name": {
						"$id": "#root/scenarios/items/scenario_name", 
						"title": "Scenario_name", 
						"type": "string",
						"default": "",
						"pattern": "^.*$"
					},
					"signal": {
						"$id": "#root/scenarios/items/signal", 
						"title": "Signal", 
						"type": "array",
						"default": [],
						"items":{
							"$id": "#root/scenarios/items/signal/items", 
							"title": "Items", 
							"type": "object",
							"required": [
								"name",
								"wave",
								"data"
							],
							"properties": {
								"name": {
									"$id": "#root/scenarios/items/signal/items/name", 
									"title": "Name", 
									"type": "string",
									"default": "",
									"pattern": "^.*$"
								},
								"wave": {
									"$id": "#root/scenarios/items/signal/items/wave", 
									"title": "Wave", 
									"type": "string",
									"default": "",
									"pattern": "^.*$"
								},
								"data": {
									"$id": "#root/scenarios/items/signal/items/data", 
									"title": "Data", 
									"type": "array",
									"default": [],
									"items":{
										"$id": "#root/scenarios/items/signal/items/data/items", 
										"title": "Items", 
										"type": "string",
										"default": "",
										"pattern": "^.*$"
									}
								},
								"source_name": {
									"$id": "#root/scenarios/items/signal/items/source_name", 
									"title": "Source_name", 
									"type": "string",
									"default": "",
									"pattern": "^.*$"
								},
								"state_synonyms": {
									"$id": "#root/scenarios/items/signal/items/state_synonyms", 
									"title": "Aliases",
									"type": "array",
									"default": [],
									"items": {
										"$id": "#root/scenarios/items/signal/items/state_synonyms/items",
										"title": "Items",
										"type": "object",
										"required": [
											"original_state_names",
											"json_state_name"
										],
										"properties": {
											"original_state_name": {
												"$id": "#root/scenarios/items/signal/items/state_synonyms/items/original_state_name",
												"title": "Original state name",
												"type": "array"
											},
											"json_state_name": {
												"$id": "#root/scenarios/items/signal/items/state_synonyms/items/json_state_name",
												"title": "JSON state name",
												"type": "string"
											}
										}
									}
								}
							}
						}

					},
					"config": {
						"$id": "#root/scenarios/items/config", 
						"title": "Config", 
						"type": "object",
						"required": [
							"hscale"
						],
						"properties": {
							"hscale": {
								"$id": "#root/scenarios/items/config/hscale", 
								"title": "Hscale", 
								"type": "integer",
								"default": 0
							}
						}
					}

				}
			}

		}
	}
}

=== Zvord/Censor.DV/jsons/real_example.json
{
  "$schema": "../mySchema.json",
  "class_name": "weather_coverage",
  "enum_name": "weather_cg_enum",
  "covergroup_name": "weather_scenario_cg",
  "fsm_descriptions": [
    {
      "source_name": "weather_fsm0",
      "valid_states": ["SUNNY", "CLOUDY", "RAIN", "SNOW", "HAIL"]
    },
    {
      "source_name": "weather_fsm1",
      "valid_states": ["SUNNY", "CLOUDY", "RAIN", "SNOW", "HAIL"]
    },
    {
      "source_name": "leisure_fsm",
      "valid_states": ["WALK","SLEEP","MOVIE","CAFE","BIKE"]
    }
  ],
    "scenarios": [
      {
        "description": "Sudden rain during a sunny day",
        "scenario_name": "SUN_RAIN_SUN",
        "signal": [
          {
            "name": "Weather",
            "wave": "2.3.4.",
            "data": ["SUNNY","RAIN","SUNNY"],
            "source_name": "weather_fsm0"
          }
        ],
        "config": {
          "hscale": 2
        }
      },
      {
        "description": "Eclipse in the rain",
        "scenario_name": "ECLIPSE_EVENT",
        "signal": [
          {
            "name": "Weather",
            "wave": "2.3.4.",
            "data": ["RAIN","SUNNY","RAIN"],
            "event_name": "Weather event",
            "source_name": "weather_fsm0"
          },
          {
            "name": "Weather event",
            "wave": "0.2.0.",
            "data": ["ECLIPSE"]
          }
        ]
      },
      {
        "description": "ALIASES_EXAMPLE",
        "scenario_name": "PRECIPATION_ON_OFF",
        "signal": [
          {
            "name": "Weather",
            "source_name": "weather_fsm0",
            "wave": "2.3.4.2.",
            "data": ["PRECIP_ON","PRECIP_OFF","PRECIP_ON","PRECIP_OFF"],
            "state_synonyms": [
              {
                "original_state_names": ["HAIL", "RAIN", "SNOW"],
                "json_state_name": "PRECIP_ON"
              },
              {
                "original_state_names": ["SUNNY", "CLOUDY"],
                "json_state_name": "PRECIP_OFF"
              }
            ]
          }
        ],
        "config": {
          "hscale": 2
        }
      },
      {
        "description": "Example of states' intersection",
        "scenario_name": "WEATHER_CROSS",
        "signal": [
          {
            "name": "Weather in London",
            "source_name": "weather_fsm0",
            "wave": "333",
            "data": ["RAIN","CLOUDY","SUNNY"],
            "node": "..A"
          },
          {
            "name": "Weather in Paris",
            "wave": "44.4",
            "data": ["HAIL","SUNNY","HAIL"],
            "node": "..B",
            "source_name": "weather_fsm1"
          }
        ],
        "edge": [
          "A~-B"
        ],
        "config": {
          "hscale": 2
        }
      },
      {
        "description": "Demonstrate exact event sequence coverage",
        "scenario_name": "EXACT_EVENT",
        "signal": [
          {
            "name": "weather_fsm0",
            "wave": "2.3.4.",
            "data": ["CLOUDY","HAIL","RAIN"],
            "event_name": "My life event"
          },
          {
            "name": "My life event",
            "wave": "0.20..",
            "data": ["Run for beer"],
            "need_exact_sequence": 1
          }
        ],
        "config": {
          "hscale": 2
        }
      },      
      {
        "description": "Full intersection example",
        "scenario_name": "FULL_INTERSECT",
        "full_intersection": [
          [
            "weather_fsm0",
            "weather_fsm1"
          ]
        ],
        "signal": [
          {
            "name": "weather_fsm0",
            "wave": "4.4.4....",
            "data": ["SUNNY","RAIN","SUNNY","RAIN"]
          },
          {
            "name": "weather_fsm1",
            "wave": "939..3.",
            "data": ["RAIN","SUNNY","RAIN","SUNNY"]
          }
        ],
        "config": {
          "hscale": 2
        }
      }
    ]
  }

=== Zvord/Censor.DV/jsons/simple_example.json
{
  "$schema": "../mySchema.json",
  "class_name": "simple_example_coverage",
  "enum_name": "enum_type_that_will_be_covered",
  "covergroup_name": "just_a_covergroup",
  "fsm_descriptions": [
    {
      "source_name": "fsm_0",
      "valid_states": ["state_a", "state_b", "state_c"]
    },
    {
      "source_name": "fsm_1",
      "valid_states": ["state_1", "state_2"]
    }
  ],
  "scenarios": [
    {
      "scenario_name": "some_name",
      "description": "A simple example",
      "signal": [
        {
          "name": "Pretty FSM 0 name",
          "source_name": "fsm_0",
          "wave": "2.3.4.",
          "data": [ "state_a", "state_b", "state_c" ],
          "event_name": "FSM 0 event",
          "node": "..a"
        },
        {
          "name": "Pretty FSM 1 name",
          "source_name": "fsm_1",
          "wave": "2..3.4",
          "data": [ "state_1", "state_2", "state_1" ],
          "node": "...b"
        },
        {
          "name": "FSM 0 event",
          "wave": "0.20..",
          "data": [ "BOOM" ]
        }
      ],
      "edge": ["a~-b"],
      "config": { "hscale": 2 }
    }
  ]
}
